[rtpengine]
interface = 103.216.119.180
listen-ng = 0.0.0.0:2223
listen-cli = 0.0.0.0:2224
foreground = true
log-level = 6
log-stderr = true

#log-srtp-keys = true
log-facility = local0
silent-timeout = 3600

[rtp]
port-min = 10000
port-max = 20000
