app_name: "Janus call service"
port: 4004
jwt_key: ${JWT_KEY}
expire_verify_token_ms: 172800000

mongodb:
  host: ${MONGODB_HOST}
  port: ${MONGODB_PORT}
  username: ${MONGODB_USERNAME}
  password: ${MONGODB_PASSWORD}
  db_name: ${MONGODB_NAME}

janus:
  http_uri: http://127.0.0.1:8088/janus
  admin_uri: http://127.0.0.1:7088/admin
  api_secret: janus-secret
  admin_secret: janus-admin

sip_transport:
  port: 9982
  public_ip: "103.216.119.180"